version: "3.8"
services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork

  devops:
    image: waelbouwazra/waelbouwazra_5twin2:1.0
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "9095:9095"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/waelbouwazra?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./m2:/root/.m2
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  db: